Project10/urls.py
from django.contrib import admin
from django.urls import path,include

from Generic.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Tirupathi/',Tirupathi,name='Tirupathi'),
    path('Tirumala/',Tirumala,name='Tirumala'),

    path('specific/',include('specific.urls')),

    # path('Specific/',include('Specific.urls')),
]

specific/urls.py
from specific.views import*
from django.urls import path
app_name='some'

urlpatterns=[
    path('sweety/',sweety,name='sweety'),
    # path('babblu/',babblu,name='babblu'),
]

Generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

Generic/views.py
from django.shortcuts import render

# Create your views here.
def Tirupathi(request):
    return render(request,'Tirupathi.html')

def Tirumala(request):
    return render(request,'Tirumala.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def sweety(request):
    return render(request,'sweety.html')

templates/Tirumala.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>In Tirumala 🙏 LORD VENKATESWARA Swamy🙏 temple </h1>
        <h1>The Lord Balaji temple is located in SevenHill's top of the Hill</h1>
        <h1>It is famous temple of us and So many people's are like to visit that temple</h1>
        <h1>Om Namo Venkatesaya</h1>
        <a href="{% url 'Tirupathi' %}"><h2>Go Back to Home safe</h2></a>
        <a href="{% url 'some:sweety' %}"><h2>Go to sweety</h2></a> 
    </center>
</body>
</html>

templates/Tirupathi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>One of the best place never ever i forget in my life</h1>
        <h1>i'm loved the place are present in Tirupathi environment</h1>
        <a href="{% url 'Tirumala' %}"><h2>Visit Tirumala atleast once's your Life</h2></a>
        <a href="{% url 'some:sweety' %}"><h2>Go to sweety</h2></a> 
    </center>
</body>
</html>

templates/babblu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Myself sweety Brother</h1>
        <!-- <a href="{% url 'some:sweety' %}"><h1></h1></a> -->
    </center>
</body>
</html>

templates/sweety.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>My self Allukuru</h1>
        <a href="{% url 'Tirupathi' %}"><h2>Back to Tirupathi</h2></a>
    </center>
</body>
</html>